version: '3.1'
services:
  springboot:
    image: dockerhandson/moinuddin06/maven-webapp-container:TAG
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
